modLoader="javafml"
loaderVersion="${forge_loader_version_range}"
license="All rights reserved"
issueTrackerURL="https://github.com/TwelveIterationMods/RefinedRelocation2/issues"

[[mods]]
modId="refinedrelocation"
version="${file.jarVersion}"
displayName="Refined Relocation"
displayURL="https://mods.twelveiterations.com/mc/refined-relocation"
logoFile="refinedrelocation-icon.png"
credits="BlayTheNinth"
authors="BlayTheNinth"
description='''
Adds sorting networks, filter systems, block extenders and more.
'''

[[dependencies.refinedrelocation]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.refinedrelocation]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.refinedrelocation]]
    modId="balm"
    mandatory=true
    versionRange="${balm_version_range}"
    ordering="NONE"
    side="BOTH"
